metadata description = 'Public Orders API VM with private PostgreSQL Flexible Server, Azure Monitor, and a read-only Azure SRE Agent.'

targetScope = 'resourceGroup'

@description('Azure region for all workshop resources.')
param location string = resourceGroup().location

@description('Deterministic lowercase alphanumeric suffix for this workshop environment.')
@minLength(3)
@maxLength(12)
param suffix string

@description('Object ID of the attendee or service principal deploying the workshop.')
@minLength(1)
param deployerPrincipalId string

@allowed([
  'User'
  'ServicePrincipal'
])
param deployerPrincipalType string = 'User'

@description('SSH public key generated by preup. There is no inbound SSH access; administration uses Run Command.')
@secure()
@minLength(1)
param vmSshPublicKey string

@description('Non-burstable VM size. An alternative size must support the x64 Gen2 Ubuntu image.')
param vmSize string = 'Standard_D2as_v5'

@description('Optional email address for Azure Monitor alert notifications.')
param alertEmail string = ''

@description('Tags applied to workshop resources.')
param tags object = {
  workload: 'sre-agent-workshop'
  environment: 'workshop'
}

resource workspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: 'law-${suffix}'
  location: location
  tags: tags
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
    workspaceCapping: {
      dailyQuotaGb: 1
    }
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: 'appi-${suffix}'
  location: location
  tags: tags
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: workspace.id
    IngestionMode: 'LogAnalytics'
    DisableIpMasking: false
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

module network './network.bicep' = {
  name: 'orders-network'
  params: {
    location: location
    suffix: suffix
    tags: tags
  }
}

module virtualMachine './vm.bicep' = {
  name: 'orders-vm'
  params: {
    location: location
    suffix: suffix
    networkInterfaceResourceId: network.outputs.networkInterfaceResourceId
    vmSshPublicKey: vmSshPublicKey
    vmSize: vmSize
    tags: tags
  }
}

module postgresql './postgresql.bicep' = {
  name: 'orders-postgresql'
  params: {
    location: location
    suffix: suffix
    delegatedSubnetResourceId: network.outputs.postgresqlSubnetResourceId
    virtualNetworkResourceId: network.outputs.virtualNetworkResourceId
    workspaceResourceId: workspace.id
    tags: tags
  }
}

module postgresqlAdministrator './postgresql-identity.bicep' = {
  name: 'orders-postgresql-administrator'
  params: {
    serverName: postgresql.outputs.serverName
    principalId: virtualMachine.outputs.vmPrincipalId
    principalName: virtualMachine.outputs.vmName
  }
}

resource ordersVm 'Microsoft.Compute/virtualMachines@2024-03-01' existing = {
  name: 'vm-orders-${suffix}'
}

resource monitorAgent 'Microsoft.Compute/virtualMachines/extensions@2024-03-01' = {
  parent: ordersVm
  name: 'AzureMonitorLinuxAgent'
  location: location
  tags: tags
  properties: {
    publisher: 'Microsoft.Azure.Monitor'
    type: 'AzureMonitorLinuxAgent'
    typeHandlerVersion: '1.0'
    autoUpgradeMinorVersion: true
    enableAutomaticUpgrade: true
    // Omitting user-assigned authentication settings selects the VM system identity.
    settings: {}
  }
  dependsOn: [
    virtualMachine
  ]
}

resource performanceRule 'Microsoft.Insights/dataCollectionRules@2023-03-11' = {
  name: 'dcr-orders-${suffix}'
  location: location
  tags: tags
  kind: 'Linux'
  properties: {
    description: 'CPU and memory performance for the Orders API virtual machine.'
    dataSources: {
      performanceCounters: [
        {
          name: 'orders-performance'
          streams: [
            'Microsoft-Perf'
          ]
          samplingFrequencyInSeconds: 60
          counterSpecifiers: [
            'Processor(*)\\% Processor Time'
            'Processor(*)\\% IO Wait Time'
            'Memory(*)\\% Used Memory'
          ]
        }
      ]
    }
    destinations: {
      logAnalytics: [
        {
          name: 'workshop-logs'
          workspaceResourceId: workspace.id
        }
      ]
    }
    dataFlows: [
      {
        streams: [
          'Microsoft-Perf'
        ]
        destinations: [
          'workshop-logs'
        ]
      }
    ]
  }
}

resource performanceAssociation 'Microsoft.Insights/dataCollectionRuleAssociations@2023-03-11' = {
  name: 'orders-performance'
  scope: ordersVm
  properties: {
    description: 'Collect performance counters from the Orders API virtual machine.'
    dataCollectionRuleId: performanceRule.id
  }
  dependsOn: [
    virtualMachine
  ]
}

module alerts './alerts.bicep' = {
  name: 'orders-alerts'
  params: {
    location: location
    suffix: suffix
    vmName: virtualMachine.outputs.vmName
    workspaceName: workspace.name
    alertEmail: alertEmail
    tags: tags
  }
}

module sreAgent './sre-agent.bicep' = {
  name: 'workshop-sre-agent'
  params: {
    location: location
    suffix: suffix
    workspaceName: workspace.name
    appInsightsName: appInsights.name
    deployerPrincipalId: deployerPrincipalId
    deployerPrincipalType: deployerPrincipalType
    tags: tags
  }
}

output vmName string = virtualMachine.outputs.vmName
output vmResourceId string = virtualMachine.outputs.vmResourceId
output vmPrincipalId string = virtualMachine.outputs.vmPrincipalId
output vmAdminUsername string = virtualMachine.outputs.vmAdminUsername
output ordersApiFqdn string = network.outputs.publicFqdn
output ordersApiEndpoint string = 'http://${network.outputs.publicFqdn}:8080'
output publicIpAddress string = network.outputs.publicIpAddress
output publicIpResourceId string = network.outputs.publicIpResourceId
output virtualNetworkName string = network.outputs.virtualNetworkName
output virtualNetworkResourceId string = network.outputs.virtualNetworkResourceId
output networkSecurityGroupName string = network.outputs.networkSecurityGroupName
output networkSecurityGroupResourceId string = network.outputs.networkSecurityGroupResourceId
output postgresqlSubnetResourceId string = network.outputs.postgresqlSubnetResourceId
output postgresqlFaultRuleName string = network.outputs.postgresqlFaultRuleName
output postgresqlFaultRuleResourceId string = network.outputs.postgresqlFaultRuleResourceId
output postgresqlServerName string = postgresql.outputs.serverName
output postgresqlServerResourceId string = postgresql.outputs.serverResourceId
output postgresqlHost string = postgresql.outputs.serverFqdn
output postgresqlDatabase string = postgresql.outputs.databaseName
output postgresqlUser string = virtualMachine.outputs.vmName
output postgresqlPrivateDnsZoneName string = postgresql.outputs.privateDnsZoneName
output postgresqlPrivateDnsZoneResourceId string = postgresql.outputs.privateDnsZoneResourceId
output workspaceName string = workspace.name
output workspaceResourceId string = workspace.id
output workspaceCustomerId string = workspace.properties.customerId
output appInsightsName string = appInsights.name
output appInsightsResourceId string = appInsights.id
output dataCollectionRuleName string = performanceRule.name
output dataCollectionRuleId string = performanceRule.id
output actionGroupName string = alerts.outputs.actionGroupName
output actionGroupId string = alerts.outputs.actionGroupId
output sreAgentName string = sreAgent.outputs.agentName
output sreAgentResourceId string = sreAgent.outputs.agentResourceId
output sreAgentEndpoint string = sreAgent.outputs.agentEndpoint
output sreAgentPrincipalId string = sreAgent.outputs.agentPrincipalId
output sreAgentIdentityResourceId string = sreAgent.outputs.operationalIdentityResourceId
output sreAgentIdentityPrincipalId string = sreAgent.outputs.operationalIdentityPrincipalId
