metadata description = 'Single-VM Orders API workshop with a persistent data disk, Azure Monitor, and a read-only Azure SRE Agent.'

targetScope = 'resourceGroup'

@description('Azure region for all workshop resources.')
param location string = resourceGroup().location

@description('Deterministic lowercase alphanumeric suffix for this workshop environment.')
@minLength(3)
@maxLength(12)
param suffix string

@description('Object ID of the attendee or service principal deploying the workshop.')
@minLength(1)
param deployerPrincipalId string

@allowed([
  'User'
  'ServicePrincipal'
])
param deployerPrincipalType string = 'User'

@description('SSH public key generated by preup. There is no inbound SSH access; administration uses Run Command.')
@secure()
@minLength(1)
param vmSshPublicKey string

@description('Non-burstable VM size. An alternative size must support the x64 Gen2 Ubuntu image.')
param vmSize string = 'Standard_D2as_v5'

@description('Capacity of the separate SQLite data disk in GiB. Existing disks can be grown, not shrunk.')
@minValue(4)
@maxValue(1023)
param dataDiskSizeGiB int = 8

@description('Optional email address for Azure Monitor alert notifications.')
param alertEmail string = ''

@description('Tags applied to workshop resources.')
param tags object = {
  workload: 'sre-agent-workshop'
  environment: 'workshop'
}

resource workspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: 'law-${suffix}'
  location: location
  tags: tags
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
    workspaceCapping: {
      dailyQuotaGb: 1
    }
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: 'appi-${suffix}'
  location: location
  tags: tags
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: workspace.id
    IngestionMode: 'LogAnalytics'
    DisableIpMasking: false
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

module network './network.bicep' = {
  name: 'orders-network'
  params: {
    location: location
    suffix: suffix
    tags: tags
  }
}

module virtualMachine './vm.bicep' = {
  name: 'orders-vm'
  params: {
    location: location
    suffix: suffix
    networkInterfaceResourceId: network.outputs.networkInterfaceResourceId
    vmSshPublicKey: vmSshPublicKey
    vmSize: vmSize
    dataDiskSizeGiB: dataDiskSizeGiB
    tags: tags
  }
}

resource ordersVm 'Microsoft.Compute/virtualMachines@2024-03-01' existing = {
  name: 'vm-orders-${suffix}'
}

resource monitorAgent 'Microsoft.Compute/virtualMachines/extensions@2024-03-01' = {
  parent: ordersVm
  name: 'AzureMonitorLinuxAgent'
  location: location
  tags: tags
  properties: {
    publisher: 'Microsoft.Azure.Monitor'
    type: 'AzureMonitorLinuxAgent'
    typeHandlerVersion: '1.0'
    autoUpgradeMinorVersion: true
    enableAutomaticUpgrade: true
    // Omitting user-assigned authentication settings selects the VM system identity.
    settings: {}
  }
  dependsOn: [
    virtualMachine
  ]
}

resource performanceRule 'Microsoft.Insights/dataCollectionRules@2023-03-11' = {
  name: 'dcr-orders-${suffix}'
  location: location
  tags: tags
  kind: 'Linux'
  properties: {
    description: 'CPU, memory, and filesystem performance, including the SQLite mount at /var/lib/orders.'
    dataSources: {
      performanceCounters: [
        {
          name: 'orders-performance'
          streams: [
            'Microsoft-Perf'
          ]
          samplingFrequencyInSeconds: 60
          counterSpecifiers: [
            'Processor(*)\\% Processor Time'
            'Processor(*)\\% IO Wait Time'
            'Memory(*)\\% Used Memory'
            'Logical Disk(*)\\% Free Space'
            'Logical Disk(*)\\Free Megabytes'
            'Logical Disk(*)\\Disk Reads/sec'
            'Logical Disk(*)\\Disk Writes/sec'
            'Logical Disk(*)\\Disk Read Bytes/sec'
            'Logical Disk(*)\\Disk Write Bytes/sec'
          ]
        }
      ]
    }
    destinations: {
      logAnalytics: [
        {
          name: 'workshop-logs'
          workspaceResourceId: workspace.id
        }
      ]
    }
    dataFlows: [
      {
        streams: [
          'Microsoft-Perf'
        ]
        destinations: [
          'workshop-logs'
        ]
      }
    ]
  }
}

resource performanceAssociation 'Microsoft.Insights/dataCollectionRuleAssociations@2023-03-11' = {
  name: 'orders-performance'
  scope: ordersVm
  properties: {
    description: 'Collect performance counters from the Orders API virtual machine.'
    dataCollectionRuleId: performanceRule.id
  }
  dependsOn: [
    virtualMachine
  ]
}

module alerts './alerts.bicep' = {
  name: 'orders-alerts'
  params: {
    location: location
    suffix: suffix
    vmName: virtualMachine.outputs.vmName
    workspaceName: workspace.name
    alertEmail: alertEmail
    tags: tags
  }
}

module sreAgent './sre-agent.bicep' = {
  name: 'workshop-sre-agent'
  params: {
    location: location
    suffix: suffix
    workspaceName: workspace.name
    appInsightsName: appInsights.name
    deployerPrincipalId: deployerPrincipalId
    deployerPrincipalType: deployerPrincipalType
    tags: tags
  }
}

output vmName string = virtualMachine.outputs.vmName
output vmResourceId string = virtualMachine.outputs.vmResourceId
output vmPrincipalId string = virtualMachine.outputs.vmPrincipalId
output vmAdminUsername string = virtualMachine.outputs.vmAdminUsername
output dataDiskName string = virtualMachine.outputs.dataDiskName
output dataDiskResourceId string = virtualMachine.outputs.dataDiskResourceId
output ordersApiFqdn string = network.outputs.publicFqdn
output ordersApiEndpoint string = 'http://${network.outputs.publicFqdn}:8080'
output publicIpAddress string = network.outputs.publicIpAddress
output publicIpResourceId string = network.outputs.publicIpResourceId
output virtualNetworkName string = network.outputs.virtualNetworkName
output virtualNetworkResourceId string = network.outputs.virtualNetworkResourceId
output workspaceName string = workspace.name
output workspaceResourceId string = workspace.id
output workspaceCustomerId string = workspace.properties.customerId
output appInsightsName string = appInsights.name
output appInsightsResourceId string = appInsights.id
output dataCollectionRuleName string = performanceRule.name
output dataCollectionRuleId string = performanceRule.id
output actionGroupName string = alerts.outputs.actionGroupName
output actionGroupId string = alerts.outputs.actionGroupId
output sreAgentName string = sreAgent.outputs.agentName
output sreAgentResourceId string = sreAgent.outputs.agentResourceId
output sreAgentEndpoint string = sreAgent.outputs.agentEndpoint
output sreAgentPrincipalId string = sreAgent.outputs.agentPrincipalId
output sreAgentIdentityResourceId string = sreAgent.outputs.operationalIdentityResourceId
output sreAgentIdentityPrincipalId string = sreAgent.outputs.operationalIdentityPrincipalId
