metadata description = 'Ubuntu 24.04 Orders API VM and an independently managed, retained SQLite data disk.'

targetScope = 'resourceGroup'

param location string = resourceGroup().location

@minLength(3)
@maxLength(12)
param suffix string

@description('NIC with the explicit public IP used for ingress and outbound package/telemetry access.')
param networkInterfaceResourceId string

@description('SSH public key generated by preup; the private key is not required or retained.')
@secure()
@minLength(1)
param vmSshPublicKey string

@description('Non-burstable VM size; overrides must support x64 Gen2 and Trusted Launch.')
param vmSize string = 'Standard_D2as_v5'

@description('SQLite data disk capacity in GiB. Run Command mounts LUN 0 at /var/lib/orders without reformatting an existing filesystem.')
@minValue(4)
@maxValue(1023)
param dataDiskSizeGiB int = 8

@description('Linux administration account; no inbound SSH or password authentication is enabled.')
param adminUsername string = 'workshopadmin'

param tags object = {}

var vmName = 'vm-orders-${suffix}'

resource dataDisk 'Microsoft.Compute/disks@2024-03-02' = {
  name: 'disk-orders-data-${suffix}'
  location: location
  tags: tags
  sku: {
    name: 'StandardSSD_LRS'
  }
  properties: {
    creationData: {
      createOption: 'Empty'
    }
    diskSizeGB: dataDiskSizeGiB
    networkAccessPolicy: 'DenyAll'
    publicNetworkAccess: 'Disabled'
  }
}

resource vm 'Microsoft.Compute/virtualMachines@2024-03-01' = {
  name: vmName
  location: location
  tags: union(tags, {
    service: 'orders-api'
    'azd-service-name': 'orders-api'
  })
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    hardwareProfile: {
      vmSize: vmSize
    }
    storageProfile: {
      imageReference: {
        publisher: 'Canonical'
        offer: 'ubuntu-24_04-lts'
        sku: 'server'
        version: 'latest'
      }
      osDisk: {
        name: 'disk-orders-os-${suffix}'
        createOption: 'FromImage'
        caching: 'ReadWrite'
        diskSizeGB: 30
        managedDisk: {
          storageAccountType: 'StandardSSD_LRS'
        }
        deleteOption: 'Delete'
      }
      dataDisks: [
        {
          name: dataDisk.name
          lun: 0
          createOption: 'Attach'
          caching: 'None'
          managedDisk: {
            id: dataDisk.id
          }
          // Deleting the VM retains SQLite; deleting the workshop resource group removes the disk.
          deleteOption: 'Detach'
        }
      ]
    }
    osProfile: {
      computerName: vmName
      adminUsername: adminUsername
      allowExtensionOperations: true
      linuxConfiguration: {
        disablePasswordAuthentication: true
        provisionVMAgent: true
        ssh: {
          publicKeys: [
            {
              path: '/home/${adminUsername}/.ssh/authorized_keys'
              keyData: vmSshPublicKey
            }
          ]
        }
      }
    }
    securityProfile: {
      securityType: 'TrustedLaunch'
      uefiSettings: {
        secureBootEnabled: true
        vTpmEnabled: true
      }
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: networkInterfaceResourceId
          properties: {
            primary: true
            deleteOption: 'Detach'
          }
        }
      ]
    }
    diagnosticsProfile: {
      bootDiagnostics: {
        enabled: true
      }
    }
  }
}

output vmName string = vm.name
output vmResourceId string = vm.id
output vmPrincipalId string = vm.identity.principalId
output vmAdminUsername string = adminUsername
output dataDiskName string = dataDisk.name
output dataDiskResourceId string = dataDisk.id
