metadata description = 'Ubuntu 24.04 Orders API VM using a private managed PostgreSQL database.'

targetScope = 'resourceGroup'

param location string = resourceGroup().location

@minLength(3)
@maxLength(12)
param suffix string

@description('NIC with the explicit public IP used for ingress and outbound package/telemetry access.')
param networkInterfaceResourceId string

@description('SSH public key generated by preup; the private key is not required or retained.')
@secure()
@minLength(1)
param vmSshPublicKey string

@description('Non-burstable VM size; overrides must support x64 Gen2 and Trusted Launch.')
param vmSize string = 'Standard_D2as_v5'

@description('Linux administration account; no inbound SSH or password authentication is enabled.')
param adminUsername string = 'workshopadmin'

param tags object = {}

var vmName = 'vm-orders-${suffix}'

resource vm 'Microsoft.Compute/virtualMachines@2024-03-01' = {
  name: vmName
  location: location
  tags: union(tags, {
    service: 'orders-api'
    'azd-service-name': 'orders-api'
  })
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    hardwareProfile: {
      vmSize: vmSize
    }
    storageProfile: {
      imageReference: {
        publisher: 'Canonical'
        offer: 'ubuntu-24_04-lts'
        sku: 'server'
        version: 'latest'
      }
      osDisk: {
        name: 'disk-orders-os-${suffix}'
        createOption: 'FromImage'
        caching: 'ReadWrite'
        diskSizeGB: 30
        managedDisk: {
          storageAccountType: 'StandardSSD_LRS'
        }
        deleteOption: 'Delete'
      }
      dataDisks: []
    }
    osProfile: {
      computerName: vmName
      adminUsername: adminUsername
      allowExtensionOperations: true
      linuxConfiguration: {
        disablePasswordAuthentication: true
        provisionVMAgent: true
        ssh: {
          publicKeys: [
            {
              path: '/home/${adminUsername}/.ssh/authorized_keys'
              keyData: vmSshPublicKey
            }
          ]
        }
      }
    }
    securityProfile: {
      securityType: 'TrustedLaunch'
      uefiSettings: {
        secureBootEnabled: true
        vTpmEnabled: true
      }
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: networkInterfaceResourceId
          properties: {
            primary: true
            deleteOption: 'Detach'
          }
        }
      ]
    }
    diagnosticsProfile: {
      bootDiagnostics: {
        enabled: true
      }
    }
  }
}

output vmName string = vm.name
output vmResourceId string = vm.id
output vmPrincipalId string = vm.identity.principalId
output vmAdminUsername string = adminUsername
